### ISSUE TITLE
IOException Messages in Output Window of Visual Studio

### ISSUE THREAD

**Issue by virtual-maker** [Tederean/FastIOW#5]
Hallo Tederean,

when I execute a sample project, I always get a lot of IOException messages in the VS output window:

![2020-04-25 13_21_39-FastIOW - Microsoft Visual Studio](https://user-images.githubusercontent.com/56232456/80281038-a969e900-8708-11ea-9941-796e41930b84.png)

I have noticed that the exeptions in the thread ProcessIO() are thrown and caught.
Apparently the native method IowKitRead() is not successful from time to time, but this can be ignored. I would find it better to handle this case without an IOException to keep the output log clean.

As a solution in my fork I added an additional method TryReadReport(), which simply returns False in case of an error. The rest I have adapted accordingly.

The commit to this is:
https://github.com/virtual-maker/FastIOW/commit/f787b6bdb6f104565fae3909576d1f36ad1696b3

If you think the solution is good I would create a Pull Request for it.

BR Immo

**Comment by Tederean** [comment]
> Apparently the native method IowKitRead() is not successful from time to time, but this can be ignored.

This happens because timeout is set to 400 ms, for some particular reasons.

> I would find it better to handle this case without an IOException to keep the output log clean.

I've never payed much attention to output, but i think your issue is useful.

This should solve your issue:

https://github.com/Tederean/FastIOW/commit/1e5a7cfcc474db1bfd2c89586ade267455d6d7be

I wanted to make the report handling methods also thread safe, i haven't done so far. Now both problems are solved.

I've not tested my changes yet, maybe you can confirm that your outputs stays clean.

**Comment by Tederean** [comment]
Tested with success.

**Comment by virtual-maker** [comment]
I can also confirm it here. The output log with the sample projects is now clean. 
Great work, thank you very much.

BTW: Will we see a new threaded example with the thread safe methods.
